//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meteosat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("meteosat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CaptionExit {
            get {
                return ResourceManager.GetString("CaptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string CaptionHide {
            get {
                return ResourceManager.GetString("CaptionHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string CaptionShow {
            get {
                return ResourceManager.GetString("CaptionShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        internal static string DefaultOptionDesktopStyle {
            get {
                return ResourceManager.GetString("DefaultOptionDesktopStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DefaultOptionHoursToSubtract {
            get {
                return ResourceManager.GetString("DefaultOptionHoursToSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string DefaultOptionIsGridEnabled {
            get {
                return ResourceManager.GetString("DefaultOptionIsGridEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DefaultOptionMaximumRetries {
            get {
                return ResourceManager.GetString("DefaultOptionMaximumRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultOptionPassword {
            get {
                return ResourceManager.GetString("DefaultOptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qwerty.
        /// </summary>
        internal static string DefaultOptionUsername {
            get {
                return ResourceManager.GetString("DefaultOptionUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string DefaultTimerDefaultTextNoDate {
            get {
                return ResourceManager.GetString("DefaultTimerDefaultTextNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DefaultTimerInterval {
            get {
                return ResourceManager.GetString("DefaultTimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value for key {0} not found.
        /// </summary>
        internal static string DefaultValueNotFound {
            get {
                return ResourceManager.GetString("DefaultValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///URL: {0}
        ///Status: {1}
        ///Response: {2}
        ///Message: {3}.
        /// </summary>
        internal static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _grid.
        /// </summary>
        internal static string GridTextForUrl {
            get {
                return ResourceManager.GetString("GridTextForUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meteosat.jpg.
        /// </summary>
        internal static string MeteosatJpg {
            get {
                return ResourceManager.GetString("MeteosatJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.sat.dundee.ac.uk/xrit/000.0E/MSG/{0}/{1}/{2}/{3}/{0}_{1}_{2}_{3}_MSG3_16_S2{4}.jpeg.
        /// </summary>
        internal static string MeteosatURL {
            get {
                return ResourceManager.GetString("MeteosatURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model {0} could not be converted..
        /// </summary>
        internal static string ModelCouldNotBeConverted {
            get {
                return ResourceManager.GetString("ModelCouldNotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string NextRunFormat {
            get {
                return ResourceManager.GetString("NextRunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitting....
        /// </summary>
        internal static string QuittingText {
            get {
                return ResourceManager.GetString("QuittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying....
        /// </summary>
        internal static string RetryingText {
            get {
                return ResourceManager.GetString("RetryingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SendWinIniChange {
            get {
                return ResourceManager.GetString("SendWinIniChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SetDesktopWallpaper {
            get {
                return ResourceManager.GetString("SetDesktopWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///URL: {0}
        ///Status: success.
        /// </summary>
        internal static string SuccessFormat {
            get {
                return ResourceManager.GetString("SuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TileWallpaper.
        /// </summary>
        internal static string Tilewallpaper {
            get {
                return ResourceManager.GetString("Tilewallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string TilewallpaperValueFalse {
            get {
                return ResourceManager.GetString("TilewallpaperValueFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string TilewallpaperValueTrue {
            get {
                return ResourceManager.GetString("TilewallpaperValueTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrayIcon.
        /// </summary>
        internal static string TrayIconResourceName {
            get {
                return ResourceManager.GetString("TrayIconResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse default value {0} for key {1} to {2}.
        /// </summary>
        internal static string UnableToParseDefaultValueForKeyTo {
            get {
                return ResourceManager.GetString("UnableToParseDefaultValueForKeyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse Style from value {0}.
        /// </summary>
        internal static string UnableToParseStyleFromValue {
            get {
                return ResourceManager.GetString("UnableToParseStyleFromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse StyleViewModel from value {0}.
        /// </summary>
        internal static string UnableToParseStyleviewmodelFromValue {
            get {
                return ResourceManager.GetString("UnableToParseStyleviewmodelFromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string UParam {
            get {
                return ResourceManager.GetString("UParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UpdateIniFile {
            get {
                return ResourceManager.GetString("UpdateIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}00.
        /// </summary>
        internal static string UrlNoFillFormat {
            get {
                return ResourceManager.GetString("UrlNoFillFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}.
        /// </summary>
        internal static string UrlZeroFormat {
            get {
                return ResourceManager.GetString("UrlZeroFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewModel {0} could not be converted..
        /// </summary>
        internal static string ViewmodelCouldNotBeConverted {
            get {
                return ResourceManager.GetString("ViewmodelCouldNotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel\Desktop.
        /// </summary>
        internal static string WallpaperRegistryKey {
            get {
                return ResourceManager.GetString("WallpaperRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallpaperStyle.
        /// </summary>
        internal static string Wallpaperstyle {
            get {
                return ResourceManager.GetString("Wallpaperstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string WallpaperstyleStrechValue {
            get {
                return ResourceManager.GetString("WallpaperstyleStrechValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string WallpaperstyleValueCenter {
            get {
                return ResourceManager.GetString("WallpaperstyleValueCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string WallpaperstyleValueFit {
            get {
                return ResourceManager.GetString("WallpaperstyleValueFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string WallpaperstyleValueTile {
            get {
                return ResourceManager.GetString("WallpaperstyleValueTile", resourceCulture);
            }
        }
    }
}
